[package]
name = "ashfall-rendering"
version.workspace = true
edition.workspace = true

[lib]
name = "ashfall_rendering"
path = "src/lib.rs"

[dependencies]
ashfall-core = { path = "../ashfall-core" }
ashfall-human = { path = "../ashfall-human" }
vulkano = "0.35.2"
vulkano-shaders = "0.35.0"
vulkano-util = "0.35.0"
winit = "0.30.13"
